### ISSUE TITLE
마일스톤 open issue와 close issue에서 profile image와 생성일 표시

### ISSUE THREAD

**Issue by javajigi** [I-Think-Not/I-Think-Not#197]
마일스톤 open issue와 close issue에서 profile image가 같은 이미지로 나타나네요.

이슈 생성일이 정상적으로 표시되지 않고 있네요.

<img width="477" alt="2017-02-17 9 42 47" src="https://cloud.githubusercontent.com/assets/520500/23047835/a686d75a-f4f5-11e6-8d73-7d0aa136ad35.png">

**Comment by box327** [comment]
처리중입니다
